name: Build Docker
on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          tags: fewald/nginx-php7
